import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar definition matching Course Curriculum
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Section 0: Introduction',
      collapsible: true,
      collapsed: false,
      items: [
        'intro/why-physical-ai',
        'intro/core-objectives'
      ],
    },
    {
      type: 'category',
      label: 'Section 1: Hardware Setup',
      collapsible: true,
      collapsed: false,
      items: [
        'hardware/requirements',
        'hardware/edge-kit',
        'hardware/robot-lab',
        'hardware/cloud-vs-local'
      ],
    },
    {
      type: 'category',
      label: 'Section 2: Foundations',
      items: ['modules/week1-2-foundations'],
    },
    {
      type: 'category',
      label: 'Section 3: ROS 2 Fundamentals',
      items: ['modules/week3-5-ros2'],
    },
    {
      type: 'category',
      label: 'Section 4: Robot Simulation',
      items: ['modules/week6-7-simulation'],
    },
    {
      type: 'category',
      label: 'Section 5: NVIDIA Isaac Platform',
      items: ['modules/week8-10-isaac'],
    },
    {
      type: 'category',
      label: 'Section 6: Humanoid Development',
      items: ['modules/week11-12-humanoid'],
    },
    {
      type: 'category',
      label: 'Section 7: Conversational Robotics',
      items: ['modules/week13-conversational'],
    },
    {
      type: 'category',
      label: 'Section 8: Assessments',
      items: ['assessments/projects'],
    },
  ],
};

export default sidebars;
